### ISSUE TITLE
Minor Issue

### ISSUE THREAD

**Issue by scotthardwick** [ewallah/moodle-availability_relativedate#1]
Hi,
Just ran across this on github and wanted to give it a try.  This would definitely help us out in Moodle.

I noticed one small item...

When I am editing the condition in the activity and I click the drop down menu , the options I get are
after course start date
before course end date
after After user enrollment date (ie, it has the word after twice)

Thanks for your work on this!

Best
Scott

**Comment by ewallah** [comment]
THX for the notice,
But beware,  this is only alpha code, a lot of work has still to be done before it can be used in production.

**Comment by ewallah** [comment]
Fixed!
