### ISSUE TITLE
Request: Add github tag for Release 3.9+

### ISSUE THREAD

**Issue by danowar2k** [ewallah/moodle-availability_relativedate#12]
Please add the tag for the new release 3.9+ (2021060600) to Github. It makes it much easier than to find the commit ids.

**Comment by danowar2k** [comment]
I guess it's this commit, isn't it? https://github.com/ewallah/moodle-availability_relativedate/tree/8b6e3d0bb304e36d8f2f328bed8e33ee0f910342

**Comment by danowar2k** [comment]
You maybe added one tag too many? (3.9+ vs. 3.9)

**Comment by ewallah** [comment]
Done.
