### ISSUE TITLE
SQL Server Compatability

### ISSUE THREAD

**Issue by advancingdesign** [ewallah/moodle-availability_relativedate#13]
I am testing the plugin on our LMS but we are one of the few with a Windows and SQL Server backend.  I had to modify the queries in the condition.php to use TOP 1 rather than limit.  I'm not sure what is the best fix in this case for global support.

SELECT TOP 1 ue.timestart
FROM {user_enrolments} ue
JOIN {enrol} e on ue.enrolid = e.id
WHERE e.courseid = :courseid AND ue.userid = :userid AND ue.timestart > 0
ORDER by ue.timestart DESC

**Comment by ewallah** [comment]
Done with tag v3.9.4

**Comment by ewallah** [comment]
Fixed by using get_record_sql with the IGNORE_MULTIPLE parameter.

THX @advancingdesign for the report.
