### ISSUE TITLE
Wrong / confusing output of get_description

### ISSUE THREAD

**Issue by malteschmitz** [ewallah/moodle-availability_relativedate#19]
The generated description for the restrictions is wrong in two cases:

1. If the course does not have an end date and I add the restriction "Student must match the following: 10 minutes before course start date" then managers get the description "This course has no end date"
  
   This happens because the code in `get_description` returns this description if `(int)$this->relativestart === 2 || (int)$this->relativestart === 6`, where 6 is _Before Course start date_. This is wrong.

2. The same code in `get_description` exchanges _from_ and _until_ for if `(int)$this->relativestart === 2 || (int)$this->relativestart === 6`, i.e. _Before Course end date_ or _Before Course start date_. This is wrong (or at least very confusing for me) because in all cases `is_available` checks `time() >= $calc` so in my opinion it is always _from_ and only _until_ if the condition is negated in the tree, i.e. `$not == true` in `get_description`.

So in my opinion this code in `get_description`

```php
if ((int)$this->relativestart === 2 || (int)$this->relativestart === 6) {
    if ((!isset($course->enddate) || (int)$course->enddate === 0) && $capability) {
        return get_string('noenddate', 'availability_relativedate');
    }
    $frut = $not ? 'from' : 'until';
} else {
    $frut = $not ? 'until' : 'from';
}
```
should become
```php
if ((int)$this->relativestart === 2 || (int)$this->relativestart === 5) {
    // In cases "2 => Before Course end date" or "5 => After Course End date"
    // show a warning if the course has no end date, but we are accessing it.
    if ((!isset($course->enddate) || (int)$course->enddate === 0) && $capability) {
        return get_string('noenddate', 'availability_relativedate');
    }
}
// Always use until if negated ($not == true) and from otherwise ($not == false)
$frut = $not ? 'until' : 'from';
```

**Comment by ewallah** [comment]
THX for the feedback. 

Indeed something is wrong in this function. However to always use until if negated is not the solution (we cannot change something that is before into an after condition).

Can you have a look at the [my solution](https://github.com/ewallah/moodle-availability_relativedate/commit/005c6164ee60c205528f9287248893807ee8143c#diff-68cf389f000a345b3f9a3fa48127930c19fe5ff4e108d37b835754cc2eef0c86L135)? Does this solve your problem?

**Comment by ewallah** [comment]
Fixed in latest release.
