### ISSUE TITLE
string api usage

### ISSUE THREAD

**Issue by ak4t0sh** [ewallah/moodle-availability_relativedate#3]
https://github.com/ewallah/moodle-availability_relativedate/blob/cfa325b5b4a611a7da4225dd9f6334f1fc330528/classes/condition.php#L158
you should use `core_text::strtolower`
see : https://docs.moodle.org/dev/String_API#strtolower

same for `substr`:
https://github.com/ewallah/moodle-availability_relativedate/blob/cfa325b5b4a611a7da4225dd9f6334f1fc330528/classes/condition.php#L146

**Comment by ewallah** [comment]
fixed

**Comment by danowar2k** [comment]
Why should strtolower be used anyway?
