### ISSUE TITLE
short ?

### ISSUE THREAD

**Issue by ak4t0sh** [ewallah/moodle-availability_relativedate#4]
I do not fully understand what "short" checkbox is supposed to do.
I think you should add an help description to explain its purpose to user. Documenting it in README could be nice too.
Moreover its edition seems pretty buggy. Steps to reproduce : 

1. Add an activity and set relative date restriction (1 day after user enrolment) with "short" checked.
2. Edit the activity and uncheck "short" then save.
3. Edit the activity again

**Expected result**
"Short" is unchecked
**Actual result**
Short is checked

Tested on 3.7.1+ (Build: 20190725)

**Comment by ewallah** [comment]
The idea to implement a short field to control the way the restriction is described (related to the $full parameter of the get_description function) was abandoned.

So this functionality was removed.
