### ISSUE TITLE
missing criteria : course completion

### ISSUE THREAD

**Issue by ak4t0sh** [ewallah/moodle-availability_relativedate#5]
Description says : 

> This availability condition makes it easy to show modules or sections only x days/weeks/months
> [...]
>     after course completion

But this criteria is not available in the select.

**Comment by ewallah** [comment]
THX ak4t0sh for the complete review.

This part of the plugin was (temporaly) removed. I spent hours explaining that the moment of course completion is also a relative moment, so "3 weeks before course completion" cannot be calculated.

When I find a simple solution to implement this, I will do so.  Until then people can use the [availability coursecompleted](https://github.com/ewallah/moodle-availability_coursecompleted) plugin.
