### ISSUE TITLE
Wrong time calculation for "after user enrolment" option

### ISSUE THREAD

**Issue by cellule-tice** [ewallah/moodle-availability_relativedate#6]
Hi there,
I think the calcdate() function (L217 in condition.php) is wrong for case 1 where it computes 60 seconds for 1 hour where it should compute 60 * 60 * x
Thus the condition is open after 1 minute rather than 1 second.
Cheers
Jean-Roch (from Namur :-))

**Comment by ewallah** [comment]
Closing as fixed!
