### ISSUE TITLE
Feature request: availability until time after enrolment

### ISSUE THREAD

**Issue by cellule-tice** [ewallah/moodle-availability_relativedate#7]
Hi, 
An interesting feature would be to allow this restriction type to give access to some activities during some time after enrolment. 
For instance "you have one week to do this assignment"
What do you think?
Cheers
Jean-Roch Meurisse

**Comment by ewallah** [comment]
Hello Jen-Roch,

I think this is already possible: when you combine a restriction with a restriction set, you can give access to an activity for a limited time. 

![capture_001_12102019_131436](https://user-images.githubusercontent.com/1324161/66700632-f8af7580-ecf2-11e9-970f-6e89907afe08.png)

![capture_002_12102019_131543](https://user-images.githubusercontent.com/1324161/66700638-0b29af00-ecf3-11e9-8b2d-9afa9a212d1a.png)

**Comment by cellule-tice** [comment]
Yes it's possible after "course start date" but it would be interesting to have it "after enrolment"
Cheers

**Comment by ewallah** [comment]
![capture_002_14102019_090138](https://user-images.githubusercontent.com/1324161/66733907-6c6f9080-ee61-11e9-9503-80b16d012f78.png)
![capture_003_14102019_090205](https://user-images.githubusercontent.com/1324161/66733914-71ccdb00-ee61-11e9-85b4-f908210cea97.png)

**Comment by ewallah** [comment]
Already implemented.
