### ISSUE TITLE
 Close resource after a period of time

### ISSUE THREAD

**Issue by samuelPsicos** [ewallah/moodle-availability_relativedate#8]
Hi there
I suggest that a resource (PDF, questionnaire, link ...) can be closed after some time has passed since enrollment in the course.
And that there is an option to open on one date and to close on another.

for example
A pdf opens 3 days after enrollment in the course and closes 7 days after enrollment in the course, that the resource is only available 4 days (hours, weeks, months, years ...)

Thanks a lot

**Comment by ewallah** [comment]
This functionality was there from the beginning: use a restriction set:
![screen_001](https://user-images.githubusercontent.com/1324161/99875086-2ac92180-2bed-11eb-9af9-90d274609adc.jpg)
Has this result
![screen_002](https://user-images.githubusercontent.com/1324161/99875134-927f6c80-2bed-11eb-9b7c-71e97cfe7987.jpg)
