### ISSUE TITLE
 International Spanish Translation.

### ISSUE THREAD

**Issue by samuelPsicos** [ewallah/moodle-availability_relativedate#9]
Hi.
We could translate the plugin into International Spanish.

If you have the texts I could help you with the translation

**Comment by ewallah** [comment]
Hi Samuel,

THX for your suggestion.

[Translating](https://docs.moodle.org/dev/Contributing_a_translation) the plugin is done by using [AMOS](https://lang.moodle.org/). This procedure ensures that the translation will be reviewed by a native speaker.

If you register, you will see that you will be able to provide the spanish international translation for this plugin - but also for other ones.  Stage your work and normally in a week your translations will be reviewed and automatically distributed over all Moodle installations who use the es-int language...

Greetings,
R

**Comment by ewallah** [comment]
Translation finally accepted in AMOS.
